[build]
publish = "."
functions = "netlify/functions"

  [build.environment]

[functions]

  [functions."*"]

[[redirects]]
from = "/detector"
to = "/detector.html"
status = 200
force = false

[[redirects]]
from = "/kalahari"
to = "/kalahari.html"
status = 200
force = false

[[redirects]]
from = "/broadcast"
to = "/index.html?entry=direct"
status = 200
force = false
